### PR TITLE
Post Events

### PR DESCRIPTION
**Pull request by spiffyjr**
* Added post events to renderEntity and renderCollection
* Each event includes a 'payload' param that's an ArrayObject (to keep
  state). They also include entity/collection params, respectively, if in
  case the original entity/collection is needed.

### CODE REVIEW

**Comment by weierophinney** [comment]
It occurs to me that we can tag 1.1 on this repo at any time; version is not tied to Apigility. Going to merge to develop and do a 1.1.0 release.

**Comment by weierophinney** [comment]
Not ready to tag 1.1 yet, as we have some stuff left to do to tag 1.0.5. However, if you want to, you can pin to `~1.1-dev@dev` or `dev-develop@dev`.

**Comment by spiffyjr** [comment]
Thank you.

**Comment by danielstqry** [comment]
These changes seem to have disappeared? It looks like a87fe327770550fd25607de999591374c9bf4eb0 (compared to b5ef0b186c8d945daf308e5aab90abecda7e11f1) had overwritten develop with master instead of merging. Any ideas?

**Comment by danielstqry** [comment]
Ping @weierophinney Any clue why this isn't in develop anymore?

**Pull request closed without merging**
