### PR TITLE
Bad service name declaration in configuration file

### PR DESCRIPTION
**Pull request by neeckeloo**
@weierophinney I have not time to test the module in Apigility context but I think the last release is not stable because of wrong declaration of services.

### CODE REVIEW

**Comment by weierophinney** [comment]
These are fine.

The file now declares itself in the `ZF\Hal` namespace. PHP, when it encounters a `::class` reference will resolve the given name based on the namespace and/or import statements, regardless of whether or not the class actually exists. If you want to give it a try:

```php
<?php
namespace Foo\Bar;

echo Baz::class, "\n";
```

This will emit:

```text
Foo\Bar\Baz
```

**Comment by neeckeloo** [comment]
I know the behavior of namespaces but in our case the alias declared is not the good one to satisfy following usage of class constant in sub namespaces.

For instance, there is a ```ZF\Hal\JsonRenderer``` service according to ```ZF\Hal\View\HalJsonRenderer``` class and now we declare it like that:

```php
namespace ZF\Hal;
 
return [
    'zf-hal' => [
        'service_manager' => [
            'factories' => [
                JsonRenderer::class => Factory\HalJsonRendererFactory::class,
            ],
        ],
    ],
];
```

The class ```ZF\Hal\JsonRenderer``` does not exist and even if we declare service with ```View\HalJsonRenderer::class```, the service name would become ```ZF\Hal\View\HalJsonRenderer``` instead of ```ZF\Hal\JsonRenderer```.

My reasoning is not good?

**Comment by neeckeloo** [comment]
ping @weierophinney

**Comment by neeckeloo** [comment]
@weierophinney Could you take a look to this possible issue please?

**Comment by dstockto** [comment]
@neeckeloo What version of PHP are you running on?

**Pull request closed without merging**
