### PR TITLE
Content-Type fix for ApiProblem while rendering

### PR DESCRIPTION
**Pull request by Wilt**
This pull request is fixing the wrong Content-Type response header when returning ApiProblem while rendering (for example api-problems returned by the Hal Plugin).

### CODE REVIEW

**Comment by snapshotpl** [comment]
@Wilt can you add falling test?

**Comment by snapshotpl** [comment]
@Wilt ping

**Comment by Wilt** [comment]
I pushed a fix for the test. All is fine now...
I also added a test for content-type in case of rendering an ApiProblemResponse

**Comment by snapshotpl** [comment]
@weierophinney can we merge it? It's very annoying bug

**Comment by snapshotpl** [comment]
@weierophinney ping

**Comment by snapshotpl** [comment]
@weierophinney @ezimuel Can anyone to check this and release fixed version? I have reported this issue in my internal bug tracker and everybody ping me to fix it ;(

**Comment by Wilt** [comment]
@snapshotpl It seems nothing is happening already for quite some time now in almost all `zf-campus` modules. I am also waiting for some issues to be solved and PRs to be merged.

**Comment by snapshotpl** [comment]
I see that @TomHAnderson merge something in Doctrine query builder.

**Pull request merged**
