### PR TITLE
force_show_links parameter added for remove links property

### PR DESCRIPTION
**Pull request by kaganuk**
Solution for this problem -> https://stackoverflow.com/questions/52855365/remove-links-property-from-embedded-resources-on-zf-rest-module
@weierophinney

### CODE REVIEW

**Comment by rnglab** [comment]
In our case we just need to disable hal links in entity. With @kaganuk's pr, finally we'll be able to manage hal links in entity with parameter `force_show_links`.

**Comment by weierophinney** [comment]
This patch requires unit tests; I'm unsure what to expect when that flag is toggled at this point, even with the `README.md` change (which is quite vague).

**Comment by Wilt** [comment]
This solution/change is not desirable IMO. 

If you want your objects to render without `_links` and without a `self` link you are most likely not rendering a Hal entity. For such cases you should consider not adding a hydrator and metadata for your class and you should consider implementing a `JsonSerializable` interface instead so the extractor will extract it using the `jsonSerialize` method. I added an answer to the question on StackOverflow, please check [the proposed solution](https://stackoverflow.com/a/56323705/1697459) and comment if it doesn't suffice your needs.

**Comment by Wilt** [comment]
[OP from the StackOverflow question mentioned in this issue managed to solve his problem](https://stackoverflow.com/questions/52855365/remove-links-property-from-embedded-resources-on-zf-rest-module/56323705?noredirect=1#comment99285677_56323705) with `JsonSerializable` as suggested in my answer on that post...

In my opinion this PR can be closed.

**Pull request closed without merging**
