### PR TITLE
Improve pagination link creation

### PR DESCRIPTION
**Pull request by neeckeloo**
We could go further by assigning this responsibility to another class and indeed isolate this behavior.
- `ZF\Hal\Link\PaginationInjector`
- `ZF\Hal\Link\PaginationManager`

### CODE REVIEW

**Comment by weierophinney** [comment]
@neeckeloo I really like this — but I think you're right, extracting one or more classes would be even better. Go for it, and update the PR when you have code to review!

**Comment by neeckeloo** [comment]
@weierophinney The PR is ready for code review.
I wonder if I should not change visibility of some methods (`injectSelfLink`, `injectFirstLink`, `injectLastLink`, `injectPrevLink`, `injectNextLink`) to public.

**Comment by weierophinney** [comment]
@neeckeloo Can you rebase and push, please? I just did a new version that ups the minimum supported version to 5.5, which includes converting long-form to short-form array notation. Thanks!

**Comment by neeckeloo** [comment]
@weierophinney PR rebased.

**Pull request closed without merging**
