### PR TITLE
Add basic functionality for URI templates

### PR DESCRIPTION
**Pull request by Merenptah**
Add possibility to define two basic URI templates to append at the end of URL of links:
1. a query in form of '{?id,id2}'
2. a path segment in form of '/{id}/{id2}"

### CODE REVIEW

**Comment by Wilt** [comment]
How would this render in the output? Can you give a  JSON example?

**Comment by Merenptah** [comment]
Hi Wilt,

sorry for the delay. An example would be
```javascript
{
  "name": "Apigility landing page",
  "_links": {
    "pizza": {
      "templated": true,
      "href": "http://apigility.local/pizza/{pizzaName}"
    },
    "pizzas by size": {
      "templated": true,
      "href": "http://apigility.local/pizza{?size}"
    },
    "pizzas": {
      "href": "http://apigility.local/pizza"
    },
    "self": {
      "href": "http://apigility.local/"
    }
  }
}
```

The relations 'pizza' and 'pizzas by size' are templated with path segment and query respectively.
What do you mean by 'relation to the self link'?

**Comment by Wilt** [comment]
I like it a lot...
Seems to follow the [HAL-Json templating ](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5.2) as mentioned in the documentation.

**Comment by Wilt** [comment]
Please correct me if I am wrong, but I think your solution doesn't allow templating as follows:

     "href": "http://apigility.local/objects/{id}/something

Since you glue the templated part of the url always at the end of the rendered url:

    $object->getUrl() . $object->getFormattedUriTemplate();

Would it not be possible to render the url like normally using the `LinkUrlBuilder` but with merging the route params with the `pathSegment` from the template?

Something in the line of:

```````````````````
    $routeParams = $object->getRouteParams();
    $templateParams = $temlate->getPathSegmentParameters();

    $params = array_merge($routeParams, $templateParams);

    $representation['href'] = $this->linkUrlBuilder->buildLinkUrl(
        $object->getRoute(),
        $params,
        $options,
        $reuseMatchedParams
    );

**Comment by Merenptah** [comment]
Hi,

as you mentioned correctly, this is not possible with my implementation. I chose to firstly only implement the most basic functionality. 
As a matter of fact it matters where you build the url, because there happens quite some escaping at some point. Can't check it right now.
But since I'm not sure if this project is still alive, I don't want to spend much time here...

**Comment by weierophinney** [comment]
@Merenptah I'd love to have some form of templating in place. However, as @Wilt notes, it's really only useful if we allow templated segments anywhere in the URI.

If you have time to add that to this PR, I'll review when ready and release!

Thanks!

**Comment by Merenptah** [comment]
As I see it this would require a complete rewrite of the URL definition mechanism, I do not even see how to configure arbitrary templating. And since I do not use ZF anymore and it took over a year to respond to the PR, I do not want to spend the time. If anyone else wants to try, I certainly could lend a hand.

**Pull request closed without merging**
